{
    "data": [
        {
        "id": "1",
        "name": "Emma Smith",
        "email": "smith@kpmg.com",
        "user_type": "vendor",
        "profile_img": "300-6.jpg",
        "cover_img": "",
        "phone": "8287110840",
        "gender": "Male",
        "country": "India",
        "state": "New Delhi",
        "city": "Shahdara",
        "flag_icon": "india.svg",
        "address": "B-97/23, Second Floor, Shahdara",
        "country_code": "91",
        "browser": "Chrome - Windows",
        "browser_version": "11.0",
        "ip_address": "49.36.200.34",
        "kyc": "Not Verified",
        "last_login": "5 hours ago",
        "created_at": "22 Sep 2022, 6:43 am",
        "status": "inactive",
        "booked_hoardings": "150",
        "sold_hoardings": "206",
        "request_hoardings": "140",
        "approved_hoardings": "165",
        "declined_hoardings": "35",
        "new_hoardings": "15"
        },
        {
        "id": "2",
        "name": "John Kumar",
        "email": "kishs@mail.com",
        "user_type": "user",
        "profile_img": "300-8.jpg",
        "cover_img": "",
        "phone": "8287161281",
        "gender": "Male",
        "country": "India",
        "state": "New Delhi",
        "city": "Shahdara",
        "flag_icon": "india.svg",
        "address": "B-97/23, Second Floor, Shahdara",
        "country_code": "91",
        "browser": "Chrome - Windows",
        "browser_version": "11.0",
        "ip_address": "67.33.200.34",
        "kyc": "Verified",
        "last_login": "5 hours ago",
        "created_at": "22 Sep 2022, 6:43 am",
        "status": "active",
        "booked_hoardings": "150",
        "sold_hoardings": "206",
        "request_hoardings": "140",
        "approved_hoardings": "165",
        "declined_hoardings": "35",
        "new_hoardings": "15"
        }
    ]
}
